const ADD_PROJECT = 'ADD_PROJECT';
const RESET_PROJECT = 'RESET_PROJECT';
const DELETE_PROJECT = 'DELETE_PROJECT';
const RENAME_PROJECT = 'RENAME_PROJECT';
export default {
	ADD_PROJECT,
	DELETE_PROJECT,
	RENAME_PROJECT,
	RESET_PROJECT
}