const ADD_TASK = 'ADD_TASK';
const DELETE_TASK = 'DELETE_TASK';
const RENAME_TASK = 'RENAME_TASK';
const COMPLETED_TASK ='COMPLETED_TASK';
const RESET_TASKS = 'RESET_TASKS';

export default {
  ADD_TASK,
  DELETE_TASK,
  RENAME_TASK,
  COMPLETED_TASK,
  RESET_TASKS
}
