const ADD_TASK = 'ADD_TASK';
const DELETE_TASK = 'DELETE_TASK';
const CHANGE_ELEMENT_TASK = 'CHANGE_ELEMENT_TASK';
const COMPLETED_TASK ='COMPLETED_TASK';
const RESET_TASKS = 'RESET_TASKS';

export default {
  ADD_TASK,
  DELETE_TASK,
  CHANGE_ELEMENT_TASK,
  COMPLETED_TASK,
  RESET_TASKS
}
